### ISSUE TITLE
refactor emailing process and improve email html

### ISSUE THREAD

**Issue by irls-svg** [Mistyttm/cutiebot#10]

**Comment by irls-svg** [comment]
@Mistyttm would you be able to test (https://github.com/Mistyttm/cutiebot/commit/06c6063226407ba3fde93a0d63129cf679eaf0c3), having issues with commits locally and want to verify latest push is working elsewhere

**Comment by Mistyttm** [comment]
> @Mistyttm would you be able to test the latest commit on 10-refactor-emails, having issues with commits locally and want to verify is working elsewhere

Yea of course, give me a bit to test and I'll get back to you

**Comment by Mistyttm** [comment]
@irls-svg running deploy returns this:
```cmd
npm run deploy
> cutiebot@1.0.0 deploy
> node deploy.js

file:///E:/JavaScript/cutiebot/deploy.js:17
    commands.push(command.default.data.toJSON());
                                  ^

TypeError: Cannot read properties of undefined (reading 'data')
    at file:///E:/JavaScript/cutiebot/deploy.js:17:35
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.7.0
```

and running start returns this:
```cmd
npm run start 

> cutiebot@1.0.0 start
> node index.js

loading data...
data loaded successfully.

writing data...
data written successfully.
bye!
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'
    at new NodeError (node:internal/errors:387:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1075:11)
    at defaultResolve (node:internal/modules/esm/resolve:1155:3)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ESMLoader.import (node:internal/modules/esm/loader:536:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///E:/JavaScript/cutiebot/index.js:31:5 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v18.7.0
```

I'm assuming this isn't the result you're expecting?

Here also is the latest commit
![image](https://user-images.githubusercontent.com/51770769/210505353-366abbda-1702-4e6b-a3d9-985b888a1ca6.png)

**Comment by irls-svg** [comment]
> @irls-svg running deploy returns this:
> 
> ```batchfile
> npm run deploy
> > cutiebot@1.0.0 deploy
> > node deploy.js
> 
> file:///E:/JavaScript/cutiebot/deploy.js:17
>     commands.push(command.default.data.toJSON());
>                                   ^
> 
> TypeError: Cannot read properties of undefined (reading 'data')
>     at file:///E:/JavaScript/cutiebot/deploy.js:17:35
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
>     at async loadESM (node:internal/process/esm_loader:91:5)
>     at async handleMainPromise (node:internal/modules/run_main:65:12)
> 
> Node.js v18.7.0
> ```

i've created a new issue for this, i know what it's caused by as i had it occur before – added a temporary fix that i intended to come back to but forgot to create an issue for it and then forgot about it entirely. when i was going through making formatting fixes i saw it and thought it was something i added as a test and meant to remove, my bad :sweat: 

the latest commit should fix this, though you'll still be getting an error during deploy due to #13, same as with `npm start`.
